apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        env:
          - name: POSTGRES_HOST
            value: "{{ .Values.postgres.host }}"
          - name: POSTGRES_PORT
            value: "{{ .Values.postgres.port }}"
          - name: POSTGRES_DB
            value: "{{ .Values.postgres.database }}"
          - name: POSTGRES_USER
            value: "{{ .Values.postgres.user }}"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ if .Values.postgresql.secretName }}{{ .Values.postgresql.secretName }}{{ else }}{{ include "my-api-backend.fullname" . }}-postgres-secret{{ end }}
                key: password
