# templates/secret.yaml

{{- if not .Values.postgresql.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    app: {{ .Chart.Name }}
type: Opaque
data:
  password: {{ .Values.postgresql.password | b64enc }}
{{- end }}
