# Workflow to deploy upon a repository dispatch event
name: Deploy on Repository Dispatch

on:
  repository_dispatch:
    types:
      - deploy
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM using Docker Compose
        uses: appleboy/ssh-action@v0.1.5  
        env:
         GHCR_PAT: ${{ secrets.PAT }}
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e  # Exit on error

            # Login to GHCR
            echo "$GHCR_PAT" | docker login ghcr.io -u hungvvu --password-stdin

            # Change to the directory where docker-compose.yml is located
            cd /home/huvu/diagscale-todo/diagscale-todo-infra

            # Fetch and reset to the latest release branch
            git fetch --all
            git checkout release
            git reset --hard origin/release

            # Pull the latest images and recreate containers
            docker compose up -d --pull always
